-- Tabela de agendamento de checklists mensais
-- Execute este script no SQL Editor do Supabase

create table if not exists public.checklist_schedules (
  id bigint generated by default as identity primary key,
  machine_id bigint not null,
  machine_name text not null,
  operator_id bigint not null,
  operator_name text not null,
  scheduled_date date not null,
  notes text,
  status text not null default 'pending' check (status in ('pending', 'completed', 'cancelled')),
  completed_at timestamptz,
  created_by_id bigint not null,
  created_by_name text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_checklist_schedules_operator_date
  on public.checklist_schedules (operator_id, scheduled_date);

create index if not exists idx_checklist_schedules_status
  on public.checklist_schedules (status);

alter table public.checklist_schedules enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'checklist_schedules'
      and policyname = 'Allow public read checklist schedules'
  ) then
    create policy "Allow public read checklist schedules"
      on public.checklist_schedules
      for select
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'checklist_schedules'
      and policyname = 'Allow public insert checklist schedules'
  ) then
    create policy "Allow public insert checklist schedules"
      on public.checklist_schedules
      for insert
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'checklist_schedules'
      and policyname = 'Allow public update checklist schedules'
  ) then
    create policy "Allow public update checklist schedules"
      on public.checklist_schedules
      for update
      using (true)
      with check (true);
  end if;
end $$;
